# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'god_auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form") 
        self.enterButton = QtWidgets.QPushButton(Form)
        self.enterButton.setGeometry(QtCore.QRect(45, 170, 125, 23))
        self.enterButton.setObjectName("enterButton")
        self.lineEdit_hostname = QtWidgets.QLineEdit(Form)
        self.lineEdit_hostname.setGeometry(QtCore.QRect(10, 30, 200, 20))
        self.lineEdit_hostname.setObjectName("lineEdit_hostname")
        self.label_hostname = QtWidgets.QLabel(Form)
        self.label_hostname.setGeometry(QtCore.QRect(10, 10, 200, 20))
        self.label_hostname.setObjectName("label_hostname")
        self.lineEdit_user = QtWidgets.QLineEdit(Form)
        self.lineEdit_user.setGeometry(QtCore.QRect(10, 80, 200, 20))
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.label_user = QtWidgets.QLabel(Form)
        self.label_user.setGeometry(QtCore.QRect(10, 60, 200, 20))
        self.label_user.setObjectName("label_user")
        self.label_password = QtWidgets.QLabel(Form)
        self.label_password.setGeometry(QtCore.QRect(10, 110, 200, 20))
        self.label_password.setObjectName("label_password")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(10, 130, 200, 20))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Super Root"))
        self.enterButton.setText(_translate("Form", "Вход"))
        self.label_hostname.setText(_translate("Form", "Имя хоста"))
        self.label_user.setText(_translate("Form", "Логин суперпользователя"))
        self.label_password.setText(_translate("Form", "Пароль"))
