# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'car_insert.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(20, 100, 51, 16))
        self.label_25.setObjectName("label_25")
        self.cars_brand_line_edit = QtWidgets.QLineEdit(Form)
        self.cars_brand_line_edit.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.cars_brand_line_edit.setObjectName("cars_brand_line_edit")
        self.cars_id_line_edit = QtWidgets.QLineEdit(Form)
        self.cars_id_line_edit.setGeometry(QtCore.QRect(100, 40, 113, 20))
        self.cars_id_line_edit.setObjectName("cars_id_line_edit")
        self.cars_place_line_edit = QtWidgets.QLineEdit(Form)
        self.cars_place_line_edit.setGeometry(QtCore.QRect(100, 100, 113, 20))
        self.cars_place_line_edit.setObjectName("cars_place_line_edit")
        self.cars_model_line_edit = QtWidgets.QLineEdit(Form)
        self.cars_model_line_edit.setGeometry(QtCore.QRect(100, 160, 113, 20))
        self.cars_model_line_edit.setObjectName("cars_model_line_edit")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(20, 70, 51, 16))
        self.label_23.setObjectName("label_23")
        self.cars_km_line_edit = QtWidgets.QLineEdit(Form)
        self.cars_km_line_edit.setGeometry(QtCore.QRect(100, 190, 113, 20))
        self.cars_km_line_edit.setText("")
        self.cars_km_line_edit.setObjectName("cars_km_line_edit")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(20, 130, 51, 16))
        self.label_20.setObjectName("label_20")
        self.cars_year_line_edit = QtWidgets.QLineEdit(Form)
        self.cars_year_line_edit.setGeometry(QtCore.QRect(100, 130, 113, 20))
        self.cars_year_line_edit.setObjectName("cars_year_line_edit")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(20, 190, 51, 16))
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(20, 160, 51, 16))
        self.label_21.setObjectName("label_21")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(20, 220, 71, 16))
        self.label_26.setObjectName("label_26")
        self.car_owner_combo_box = QtWidgets.QComboBox(Form)
        self.car_owner_combo_box.setGeometry(QtCore.QRect(100, 220, 111, 22))
        self.car_owner_combo_box.setObjectName("car_owner_combo_box")
        self.add_button_2 = QtWidgets.QPushButton(Form)
        self.add_button_2.setGeometry(QtCore.QRect(130, 260, 75, 23))
        self.add_button_2.setObjectName("add_button_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить авто"))
        self.label_15.setText(_translate("Form", "Автомобили:"))
        self.label_25.setText(_translate("Form", "Гос №"))
        self.label_23.setText(_translate("Form", "Бренд"))
        self.label_20.setText(_translate("Form", "Год"))
        self.label_22.setText(_translate("Form", "Пробег"))
        self.label_21.setText(_translate("Form", "Модель"))
        self.label_24.setText(_translate("Form", "ID"))
        self.label_26.setText(_translate("Form", "Собственник"))
        self.add_button_2.setText(_translate("Form", "Добавить"))
