# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form") 
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_12.setObjectName("label_12")
        self.count_client_line = QtWidgets.QLineEdit(Form)
        self.count_client_line.setGeometry(QtCore.QRect(100, 10, 51, 20))
        self.count_client_line.setObjectName("count_client_line")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.client_address_line_edit = QtWidgets.QLineEdit(Form)
        self.client_address_line_edit.setGeometry(QtCore.QRect(100, 170, 113, 20))
        self.client_address_line_edit.setObjectName("client_address_line_edit")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(40, 170, 51, 16))
        self.label_21.setObjectName("label_21")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(40, 80, 51, 16))
        self.label_14.setObjectName("label_14")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(40, 140, 51, 16))
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(40, 110, 51, 16))
        self.label_22.setObjectName("label_22")
        self.client_id_line_edit = QtWidgets.QLineEdit(Form)
        self.client_id_line_edit.setGeometry(QtCore.QRect(100, 80, 113, 20))
        self.client_id_line_edit.setObjectName("client_id_line_edit")
        self.client_passport_line_edit = QtWidgets.QLineEdit(Form)
        self.client_passport_line_edit.setGeometry(QtCore.QRect(100, 140, 113, 20))
        self.client_passport_line_edit.setObjectName("client_passport_line_edit")
        self.client_name_line_edit = QtWidgets.QLineEdit(Form)
        self.client_name_line_edit.setGeometry(QtCore.QRect(100, 110, 113, 20))
        self.client_name_line_edit.setObjectName("client_name_line_edit")
        self.add_button = QtWidgets.QPushButton(Form)
        self.add_button.setGeometry(QtCore.QRect(130, 230, 75, 23))
        self.add_button.setObjectName("add_button")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(40, 200, 51, 16))
        self.label_23.setObjectName("label_23")
        self.client_phone_line_edit = QtWidgets.QLineEdit(Form)
        self.client_phone_line_edit.setGeometry(QtCore.QRect(100, 200, 113, 20))
        self.client_phone_line_edit.setObjectName("client_phone_line_edit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить клиента"))
        self.label_12.setText(_translate("Form", "Всего клиентов:"))
        self.label_13.setText(_translate("Form", "Клиент:"))
        self.label_21.setText(_translate("Form", "Адрес"))
        self.label_14.setText(_translate("Form", "ID"))
        self.label_20.setText(_translate("Form", "Паспорт"))
        self.label_22.setText(_translate("Form", "Фамилия"))
        self.add_button.setText(_translate("Form", "Добавить"))
        self.label_23.setText(_translate("Form", "Телефон"))
