# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form") 
        self.regestration_button = QtWidgets.QPushButton(Form)
        self.regestration_button.setGeometry(QtCore.QRect(10, 10, 200, 23))
        self.regestration_button.setObjectName("regestration_button")
        self.search_button = QtWidgets.QPushButton(Form)
        self.search_button.setGeometry(QtCore.QRect(10, 40, 200, 23))
        self.search_button.setObjectName("search_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Автосервис"))
        self.regestration_button.setText(_translate("Form", "Зарегистрировать"))
        self.search_button.setText(_translate("Form", "Поиск"))
