# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form") 
        self.count_client_line = QtWidgets.QLineEdit(Form)
        self.count_client_line.setGeometry(QtCore.QRect(100, 10, 51, 20))
        self.count_client_line.setObjectName("count_client_line")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")
        self.client_id_line_edit_2 = QtWidgets.QLineEdit(Form)
        self.client_id_line_edit_2.setGeometry(QtCore.QRect(70, 100, 113, 20))
        self.client_id_line_edit_2.setObjectName("client_id_line_edit_2")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_12.setObjectName("label_12")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 180, 411, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 160, 71, 16))
        self.label_13.setObjectName("label_13")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 260, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Поиск"))
        self.label.setText(_translate("Form", "Всего клиентов:"))
        self.label_12.setText(_translate("Form", "ID сервиса"))
        self.label_13.setText(_translate("Form", "Информация"))
        self.pushButton.setText(_translate("Form", "Поиск"))
        self.pushButton_2.setText(_translate("Form", "Удалить"))
