# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selected.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 170)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 120, 25))
        self.label.setObjectName("label")
        self.InsertClientButton = QtWidgets.QPushButton(Form)
        self.InsertClientButton.setGeometry(QtCore.QRect(130, 10, 80, 25))
        self.InsertClientButton.setObjectName("InsertClientButton")
        self.InsertCarButton = QtWidgets.QPushButton(Form)
        self.InsertCarButton.setGeometry(QtCore.QRect(210, 10, 80, 25))
        self.InsertCarButton.setObjectName("InsertCarButton")
        self.InsertServiceButton = QtWidgets.QPushButton(Form)
        self.InsertServiceButton.setGeometry(QtCore.QRect(290, 10, 80, 25))
        self.InsertServiceButton.setObjectName("InsertServiceButton")
        self.UpdateClientButton = QtWidgets.QPushButton(Form)
        self.UpdateClientButton.setGeometry(QtCore.QRect(130, 35, 80, 25))
        self.UpdateClientButton.setObjectName("UpdateClientButton")
        self.UpdateCarButton = QtWidgets.QPushButton(Form)
        self.UpdateCarButton.setGeometry(QtCore.QRect(210, 35, 80, 25))
        self.UpdateCarButton.setObjectName("UpdateCarButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 35, 120, 25))
        self.label_2.setObjectName("label_2")
        self.UpdateServiceButton = QtWidgets.QPushButton(Form)
        self.UpdateServiceButton.setGeometry(QtCore.QRect(290, 35, 80, 25))
        self.UpdateServiceButton.setObjectName("UpdateServiceButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Добавить запись"))
        self.InsertClientButton.setText(_translate("Form", "Клиент"))
        self.InsertCarButton.setText(_translate("Form", "Автомобиль"))
        self.InsertServiceButton.setText(_translate("Form", "Сервис"))
        self.UpdateClientButton.setText(_translate("Form", "Клиент"))
        self.UpdateCarButton.setText(_translate("Form", "Автомобиль"))
        self.label_2.setText(_translate("Form", "Обновить запись"))
        self.UpdateServiceButton.setText(_translate("Form", "Сервис"))
