# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'service_reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form") 
        self.service_problem_line_edit_2 = QtWidgets.QLineEdit(Form)
        self.service_problem_line_edit_2.setGeometry(QtCore.QRect(90, 100, 113, 20))
        self.service_problem_line_edit_2.setObjectName("service_problem_line_edit_2")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(10, 130, 51, 16))
        self.label_23.setObjectName("label_23")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.label_22.setObjectName("label_22")
        self.service_price_line_edit_2 = QtWidgets.QLineEdit(Form)
        self.service_price_line_edit_2.setGeometry(QtCore.QRect(90, 130, 113, 20))
        self.service_price_line_edit_2.setObjectName("service_price_line_edit_2")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(10, 100, 51, 16))
        self.label_21.setObjectName("label_21")
        self.service_id_line_edit_2 = QtWidgets.QLineEdit(Form)
        self.service_id_line_edit_2.setGeometry(QtCore.QRect(90, 70, 113, 20))
        self.service_id_line_edit_2.setObjectName("service_id_line_edit_2")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_13.setObjectName("label_13")
        self.count_car_line_2 = QtWidgets.QLineEdit(Form)
        self.count_car_line_2.setGeometry(QtCore.QRect(90, 10, 51, 20))
        self.count_car_line_2.setObjectName("count_car_line_2")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(10, 160, 71, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(10, 190, 71, 16))
        self.label_25.setObjectName("label_25")
        self.car_owner_combo_box_2 = QtWidgets.QComboBox(Form)
        self.car_owner_combo_box_2.setGeometry(QtCore.QRect(90, 160, 111, 22))
        self.car_owner_combo_box_2.setObjectName("car_owner_combo_box_2")
        self.car_owner_combo_box_3 = QtWidgets.QComboBox(Form)
        self.car_owner_combo_box_3.setGeometry(QtCore.QRect(90, 190, 111, 22))
        self.car_owner_combo_box_3.setObjectName("car_owner_combo_box_3")
        self.add_button_3 = QtWidgets.QPushButton(Form)
        self.add_button_3.setGeometry(QtCore.QRect(120, 230, 75, 23))
        self.add_button_3.setObjectName("add_button_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить сервис"))
        self.label_23.setText(_translate("Form", "Цена"))
        self.label_22.setText(_translate("Form", "ID"))
        self.label_21.setText(_translate("Form", "Проблема"))
        self.label_16.setText(_translate("Form", "Сервис:"))
        self.label_13.setText(_translate("Form", "Всего проблем:"))
        self.label_24.setText(_translate("Form", "Авто"))
        self.label_25.setText(_translate("Form", "Клиент"))
        self.add_button_3.setText(_translate("Form", "Добавить"))
