# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GetClient_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form") 
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 100, 25))
        self.label.setObjectName("label")
        self.searchButton = QtWidgets.QPushButton(Form)
        self.searchButton.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.searchButton.setObjectName("searchButton")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(110, 15, 100, 22))
        self.comboBox.setObjectName("comboBox")
        self.client_address_line_edit = QtWidgets.QLineEdit(Form)
        self.client_address_line_edit.setGeometry(QtCore.QRect(70, 140, 113, 20))
        self.client_address_line_edit.setObjectName("client_address_line_edit")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.label_27.setObjectName("label_27")
        self.client_name_line_edit = QtWidgets.QLineEdit(Form)
        self.client_name_line_edit.setGeometry(QtCore.QRect(70, 80, 113, 20))
        self.client_name_line_edit.setObjectName("client_name_line_edit")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(10, 110, 51, 16))
        self.label_24.setObjectName("label_24")
        self.client_passport_line_edit = QtWidgets.QLineEdit(Form)
        self.client_passport_line_edit.setGeometry(QtCore.QRect(70, 110, 113, 20))
        self.client_passport_line_edit.setObjectName("client_passport_line_edit")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(10, 170, 51, 16))
        self.label_26.setObjectName("label_26")
        self.client_phone_line_edit = QtWidgets.QLineEdit(Form)
        self.client_phone_line_edit.setGeometry(QtCore.QRect(70, 170, 113, 20))
        self.client_phone_line_edit.setObjectName("client_phone_line_edit")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(10, 140, 51, 16))
        self.label_25.setObjectName("label_25")
        self.updateButton = QtWidgets.QPushButton(Form)
        self.updateButton.setGeometry(QtCore.QRect(10, 200, 75, 23))
        self.updateButton.setObjectName("updateButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Введите ID"))
        self.searchButton.setText(_translate("Form", "Поиск"))
        self.label_27.setText(_translate("Form", "Фамилия"))
        self.label_24.setText(_translate("Form", "Паспорт"))
        self.label_26.setText(_translate("Form", "Телефон"))
        self.label_25.setText(_translate("Form", "Адрес"))
        self.updateButton.setText(_translate("Form", "Обновить"))
